import { Movie } from './IDB';
import img from '../assets/DataImage/Movie/poster_1.png'
import img2 from '../assets/DataImage/Movie/poster_2.png'
import img3 from '../assets/DataImage/Movie/poster_3.png'
import img4 from '../assets/DataImage/Movie/poster_4.png'
import img5 from '../assets/DataImage/Movie/poster_5.png'
import img6 from '../assets/DataImage/Movie/poster_6.png'
import img7 from '../assets/DataImage/Movie/poster_7.png'
import img8 from '../assets/DataImage/Movie/poster_8.png'
import img9 from '../assets/DataImage/Movie/poster_9.png'
import img10 from '../assets/DataImage/Movie/poster_10.png'
import img11 from '../assets/DataImage/Movie/poster_11.png'
import img12 from '../assets/DataImage/Movie/poster_12.png'
import img13 from '../assets/DataImage/Movie/poster_13.png'
import img14 from '../assets/DataImage/Movie/poster_14.png'
import img15 from '../assets/DataImage/Movie/poster_15.png'
import img16 from '../assets/DataImage/Movie/poster_16.png'
import img17 from '../assets/DataImage/Movie/poster_17.png'
import img18 from '../assets/DataImage/Movie/poster_18.png'
import img19 from '../assets/DataImage/Movie/poster_19.png'
import img20 from '../assets/DataImage/Movie/poster_20.png'




export const moviesData: Movie[] = [
  {
    id: 1,
    title: 'Black Doves',
    releaseDate: 'Dec 05, 2024',
    imageUrl: img,
    score: 79,
    overview: "When a spy posing as a politician's wife learns her lover has been murdered, an old assassin friend joins her on a quest for truth — and vengeance.",
    genre: ["Mystery", "Crime", "Action", "Adventure"],
    runtime: "1h 20m",
    videoUrl: 'https://youtu.be/shzJzjVscno',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 2,
    title: 'Mary',
    releaseDate: 'Dec 05, 2024',
    imageUrl: img2,
    score: 62,
    overview: "A miraculous conception. A merciless king. A murderous pursuit. Mary's journey to give birth to Jesus unfolds in this biblical coming-of-age epic.",
    genre: ["Drama", "History", "Action"],
    runtime: "1h 50m",
    videoUrl: 'https://youtu.be/d74vHvsACSs',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 3,
    title: 'The Red Virgin',
    releaseDate: 'Sep 27, 2024',
    imageUrl: img3,
    score: 71,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "History", "Thriller"],
    runtime: " 1h 54m",
    videoUrl: 'https://youtu.be/yIBvbxTj0i0',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 4,
    title: 'That Christmas',
    releaseDate: 'Dec 04, 2024',
    imageUrl: img4,
    score: 72,
    overview: "A different movie with a thrilling plot.",
    genre: ["Animation", "Comedy", "Family", "Fantasy", "Adventure"],
    runtime: "1h 31m",
    videoUrl: 'https://youtu.be/SiCTXSwqzkw',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 5,
    title: 'Commandos',
    releaseDate: 'Dec 05, 2024',
    imageUrl: img5,
    score: 74,
    overview: "A different movie with a thrilling plot.",
    genre: ["Animation", "Sci-Fi & Fantasy", "Action & Adventure"],
    runtime: "1h 10m",
    videoUrl: 'https://youtu.be/VdahDEpqPA8',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 6,
    title: 'Juror #2',
    releaseDate: 'Oct 30, 2024',
    imageUrl: img6,
    score: 70,
    overview: "A different movie with a thrilling plot.",
    genre: ["Crime", "Drama"],
    runtime: "1h 54m",
    videoUrl: 'https://youtu.be/czYUXo0R0oA',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 7,
    title: 'The Day of Jackal',
    releaseDate: 'Nov 07, 2024',
    imageUrl: img7,
    score: 82,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Action & Adventure", "Mystery"],
    runtime: "1h 10m",
    videoUrl: 'https://youtu.be/EUb_04MdnMI',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 8,
    title: 'Moana 2',
    releaseDate: 'Nov 27, 2024',
    imageUrl: img8,
    score: 69,
    overview: "A different movie with a thrilling plot.",
    genre: ["Animation", "Adventure", "Family", "Comedy"],
    runtime: "1h 40m",
    videoUrl: 'https://youtu.be/9IisFuMUz44',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 9,
    title: 'Wicked',
    releaseDate: 'Nov 20, 2024',
    imageUrl: img9,
    score: 76,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Romance", "Fantasy"],
    runtime: "2h 40m",
    videoUrl: 'https://youtu.be/pqi45Qhq3CI',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 10,
    title: 'The Childrens Train',
    releaseDate: 'Dec 04, 2024',
    imageUrl: img10,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama"],
    runtime: "1h 46m",
    videoUrl: 'https://youtu.be/76Aljh0U8Hk',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 11,
    title: 'Love Life Light',
    releaseDate: 'Dec 08, 2023',
    imageUrl: img11,
    score: 64,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Mystery", "Fantasy"],
    runtime: "1h 23m",
    videoUrl: 'https://youtu.be/E83Y6dzXph0?si=WVC51vi8T_bnfL-f',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 12,
    title: 'Star Wars: Skeleton',
    releaseDate: 'Dec 02, 2024',
    imageUrl: img12,
    score: 70,
    overview: "A different movie with a thrilling plot.",
    genre: ["Action & Adventure", "Sci-Fi & Fantasy"],
    runtime: "1h 20m",
    videoUrl: 'https://youtu.be/f19gfOMZTtg',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 13,
    title: 'The Sticky',
    releaseDate: 'Dec 06, 2024',
    imageUrl: img13,
    score: 83,
    overview: "A different movie with a thrilling plot.",
    genre: ["Comedy", "Drama"],
    runtime: "1h 20m",
    videoUrl: 'https://youtu.be/EicNAYAs8ds',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 14,
    title: 'Silo',
    releaseDate: 'May 04, 2023',
    imageUrl: img14,
    score: 82,
    overview: "A different movie with a thrilling plot.",
    genre: ["Sci-Fi & Fantasy", "Drama"],
    runtime: "1h 33m",
    videoUrl: 'https://youtu.be/8ZYhuvIv1pA',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 15,
    title: 'Arcane',
    releaseDate: 'Nov 06, 2021',
    imageUrl: img15,
    score: 88,
    overview: "A different movie with a thrilling plot.",
    genre: ["Animation", "Sci-Fi & Fantasy"," Action & Adventure", "Mystery", "Drama"],
    runtime: "1h 05m",
    videoUrl: 'https://youtu.be/W4gLFBNGgiY',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 16,
    title: 'Dear Santa',
    releaseDate: 'Nov 24, 2024',
    imageUrl: img16,
    score: 65,
    overview: "A different movie with a thrilling plot.",
    genre: ["Comedy", "Fantasy"],
    runtime: "1h 48m",
    videoUrl: 'https://youtu.be/Cr7z5Q7oJc0?si=X6_demOzK9cqWDLI',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 17,
    title: 'Day and Night',
    releaseDate: 'Aug 30, 2017',
    imageUrl: img17,
    score: 83,
    overview: "A different movie with a thrilling plot.",
    genre: ["Crime", "Drama", "Mystery"],
    runtime: "1h 13m",
    videoUrl: 'https://youtu.be/DJH6Lf8FBwc',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 18,
    title: 'Alien: Romulus',
    releaseDate: 'Aug 13, 2024',
    imageUrl: img18,
    score: 72,
    overview: "A different movie with a thrilling plot.",
    genre: ["Horror", "Science Fiction"],
    runtime: "1h 59m",
    videoUrl: 'https://youtu.be/x0XDEhP4MQs',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 19,
    title: 'Camp Crasher',
    releaseDate: 'Dec 05, 2024',
    imageUrl: img19,
    score: 67,
    overview: "A different movie with a thrilling plot.",
    genre: ["Comedy", "Romance"],
    runtime: "1h 35m",
    videoUrl: 'https://youtu.be/ZlOFh9ksLs8',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
  {
    id: 20,
    title: 'The Agency',
    releaseDate: 'Dec 01, 2024',
    imageUrl: img20,
    score: 79,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Mystery"],
    runtime: "1h 40m",
    videoUrl: 'https://youtu.be/zv817ouw7qE',
    movieUrl: 'https://www.netflix.com/in/title/81004270',
  },
];
