import { Movie } from './IDB';
import img from '../assets/image/Favicon.png';
import img2 from '../assets/image/Slider3.png';

export const moviesData: Movie[] = [
  {
    id: 1,
    title: 'Black Doves',
    releaseDate: 'Dec 05, 2024',
    imageUrl: img,
    score: 83,
    overview: "When a spy posing as a politician's wife learns her lover has been murdered, an old assassin friend joins her on a quest for truth — and vengeance.",
    genre: ["Mystery", "Crime", "Action", "Adventure"],
    runtime: 120,
  },
  {
    id: 2,
    title: 'Mary',
    releaseDate: 'Dec 05, 2024',
    imageUrl: img2,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 3,
    title: 'The Red Virgin',
    releaseDate: 'Sep 27, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 4,
    title: 'That Christmas',
    releaseDate: 'Dec 04, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 5,
    title: 'Creature Commandos',
    releaseDate: 'Dec 05, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 6,
    title: 'Juror #2',
    releaseDate: 'Oct 30, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 7,
    title: 'The Day of the Jackal',
    releaseDate: 'Nov 07, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 8,
    title: 'Moana 2',
    releaseDate: 'Nov 27, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 9,
    title: 'Wicked',
    releaseDate: 'Nov 20, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 10,
    title: 'The Childrens Train',
    releaseDate: 'Dec 04, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 11,
    title: 'Love Life Light',
    releaseDate: 'Dec 08, 2023',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 12,
    title: 'Star Wars: Skeleton Crew',
    releaseDate: 'Dec 02, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 13,
    title: 'The Sticky',
    releaseDate: 'Dec 06, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 14,
    title: 'Silo',
    releaseDate: 'May 04, 2023',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 15,
    title: 'Arcane',
    releaseDate: 'Nov 06, 2021',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 16,
    title: 'Pushpa 2 - The Rule',
    releaseDate: 'Dec 04, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 17,
    title: 'Day and Night',
    releaseDate: 'Aug 30, 2017',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 18,
    title: 'Alien: Romulus',
    releaseDate: 'Aug 13, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 19,
    title: 'Camp Crasher',
    releaseDate: 'Dec 05, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
  {
    id: 20,
    title: 'Light Shop',
    releaseDate: 'Dec 04, 2024',
    imageUrl: img,
    score: 75,
    overview: "A different movie with a thrilling plot.",
    genre: ["Drama", "Thriller"],
    runtime: 110,
  },
];
