import { TVShow } from './IDB';
import img1 from '../assets/DataImage/TV Show/Poster_1.png'
import img2 from '../assets/DataImage/TV Show/Poster_2.png'
import img3 from '../assets/DataImage/TV Show/Poster_3.png'
import img4 from '../assets/DataImage/TV Show/Poster_4.png'
import img5 from '../assets/DataImage/TV Show/Poster_5.png'
import img6 from '../assets/DataImage/TV Show/Poster_6.png'
import img7 from '../assets/DataImage/TV Show/Poster_7.png'
import img8 from '../assets/DataImage/TV Show/Poster_8.png'
import img9 from '../assets/DataImage/TV Show/Poster_9.png'
import img10 from '../assets/DataImage/TV Show/Poster_10.png'
import img11 from '../assets/DataImage/TV Show/Poster_11.png'
import img12 from '../assets/DataImage/TV Show/Poster_12.png'
import img13 from '../assets/DataImage/TV Show/Poster_13.png'
import img14 from '../assets/DataImage/TV Show/Poster_14.png'
import img15 from '../assets/DataImage/TV Show/Poster_15.png'
import img16 from '../assets/DataImage/TV Show/Poster_16.png'
import img17 from '../assets/DataImage/TV Show/Poster_17.png'
import img18 from '../assets/DataImage/TV Show/Poster_18.png'
import img19 from '../assets/DataImage/TV Show/Poster_19.png'
import img20 from '../assets/DataImage/TV Show/Poster_20.png'

export const tvShowsData: TVShow[] = [
  {
    id: 1,
    title: 'GTMAX',
    season: 1,
    episodeCount: 10,
    imageUrl: img1,
    score: 61,
    overview: "When a spy posing as a politician's wife learns her lover has been murdered, an old assassin friend joins her on a quest for truth — and vengeance.",
    genre: ["Mystery", "Crime", "Action", "Adventure"],
    runtime: 120,
    releaseDate: "Nov 19, 2024",
  },
  {
    id: 2,
    title: 'Suits',
    season: 1,
    episodeCount: 8,
    imageUrl: img2,
    score: 82,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Jun 23, 2011",
  },
  {
    id: 3,
    title: 'The Good Doctor',
    season: 1,
    episodeCount: 8,
    imageUrl: img3,
    score: 85,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Jun 23, 2011",
  },
  {
    id: 4,
    title: 'House',
    season: 1,
    episodeCount: 8,
    imageUrl: img4,
    score: 86,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Nov 16, 2004",
  },
  {
    id: 5,
    title: 'Our Little Secret',
    season: 1,
    episodeCount: 8,
    imageUrl: img5,
    score: 63,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Nov 27, 2024",
  },
  {
    id: 6,
    title: 'Young Sheldon',
    season: 1,
    episodeCount: 8,
    imageUrl: img6,
    score: 81,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Sep 25, 2017",
  },
  {
    id: 7,
    title: 'Venom',
    season: 1,
    episodeCount: 8,
    imageUrl: img7,
    score: 68,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Oct 05, 2018",
  },
  {
    id: 8,
    title: 'Supernatural',
    season: 1,
    episodeCount: 8,
    imageUrl: img8,
    score: 83,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Sep 13, 2005",
  },
  {
    id: 9,
    title: 'The Garfield Movie',
    season: 1,
    episodeCount: 8,
    imageUrl: img9,
    score: 71,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Apr 30, 2024",
  },
  {
    id: 10,
    title: 'Cobra Kai',
    season: 1,
    episodeCount: 8,
    imageUrl: img10,
    score: 82,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "May 02, 2018",
  },
  {
    id: 11,
    title: 'The Platform 2',
    season: 1,
    episodeCount: 8,
    imageUrl: img11,
    score: 56,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Oct 04, 2024",
  },
  {
    id: 12,
    title: 'Lucifer',
    season: 1,
    episodeCount: 8,
    imageUrl: img12,
    score: 68,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Jan 25, 2016",
  },
  {
    id: 13,
    title: 'The Mentalist',
    season: 1,
    episodeCount: 8,
    imageUrl: img13,
    score: 82,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Sep 23, 2008",
  },
  {
    id: 14,
    title: "Don't Move",
    season: 1,
    episodeCount: 8,
    imageUrl: img14,
    score: 64,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Oct 25, 2024",
  },
  {
    id: 15,
    title: 'Sing: Thriller',
    season: 1,
    episodeCount: 8,
    imageUrl: img15,
    score: 74,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Oct 16, 2024",
  },
  {
    id: 16,
    title: 'Law & Order:',
    season: 1,
    episodeCount: 8,
    imageUrl: img16,
    score: 79,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Sep 20, 1999",
  },
  {
    id: 17,
    title: 'Pimpinero',
    season: 1,
    episodeCount: 8,
    imageUrl: img17,
    score: 72,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Oct 10, 2024",
  },
  {
    id: 18,
    title: 'Dan Da Dan',
    season: 1,
    episodeCount: 8,
    imageUrl: img18,
    score: 89,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Oct 04, 2024",
  },
  {
    id: 19,
    title: 'Bad Boys',
    season: 1,
    episodeCount: 8,
    imageUrl: img19,
    score: 75,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Jun 05, 2024",
  },
  {
    id: 20,
    title: 'Hunting With Tigers',
    season: 1,
    episodeCount: 8,
    imageUrl: img20,
    score: 63,
    overview: "A thrilling TV show with unexpected twists.",
    genre: ["Drama", "Thriller"],
    runtime: 45,
    releaseDate: "Nov 22, 2024",
  },
];
